// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://gitee.com/MR-wind/my-obj.git",
        "contact": {
            "name": "API Support",
            "url": "https://gitee.com/MR-wind/my-obj.git/issues",
            "email": "support@myobj.com"
        },
        "license": {
            "name": "Apache-2.0",
            "url": "https://opensource.org/licenses/Apache-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/download/local/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建网盘文件下载任务，支持加密文件和分片文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "创建网盘文件下载任务",
                "parameters": [
                    {
                        "description": "下载请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.CreateLocalFileDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/download/local/file/{taskID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "下载已准备完成的网盘文件，支持HTTP Range断点续传",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "下载网盘文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Range请求头（例：bytes=0-1023）",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件流",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "206": {
                        "description": "部分文件流（Range请求）",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "任务不存在或未准备完成",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "下载失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/download/preview": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "直接预览文件（用于图片、视频、PDF等预览场景），支持HTTP Range断点续传，不创建下载任务",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "文件预览",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件ID（UserFiles的UfID）",
                        "name": "file_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件解密密码（加密文件必需）",
                        "name": "file_password",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Range请求头（例：bytes=0-1023）",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件流",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "206": {
                        "description": "部分文件流（Range请求）",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "参数错误或文件不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "无权限",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "预览失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/download/torrent/parse": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "解析种子文件或磁力链接，返回文件列表供用户选择,种子文件内容（Base64编码）或磁力链接（magnet:开头）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "解析种子/磁力链",
                "parameters": [
                    {
                        "description": "解析请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.ParseTorrentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解析成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/myobj_src_core_domain_response.ParseTorrentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "解析失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/download/torrent/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户选择的文件索引，创建下载任务并开始下载,种子文件内容（Base64编码）或磁力链接（magnet:开头）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "下载管理"
                ],
                "summary": "开始种子/磁力链下载",
                "parameters": [
                    {
                        "description": "下载请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.StartTorrentDownloadRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "任务创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/myobj_src_core_domain_response.StartTorrentDownloadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将文件移动到回收站（软删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "description": "删除请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.DeleteFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/deleteDir": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除目录及其下的所有文件和子目录（文件会移动到回收站）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除目录",
                "parameters": [
                    {
                        "description": "删除目录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.DeleteDirRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或根目录不能删除",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "目录不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户指定目录下的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取文件列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "虚拟路径",
                        "name": "virtualPath",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/public/list": {
            "get": {
                "description": "获取广场公开文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取广场公开文件列表",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.PublicFileListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/rename": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "重命名用户文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "重命名文件",
                "parameters": [
                    {
                        "description": "重命名请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.RenameFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "重命名成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或重命名失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/renameDir": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "重命名用户目录，并自动更新子目录和文件的路径",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "重命名目录",
                "parameters": [
                    {
                        "description": "重命名请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.RenameDirRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "重命名成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或重命名失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "目录不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/search/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据关键词搜索当前用户的文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "搜索当前用户文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "搜索失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/setPublic": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "设置文件是否公开（加密文件不能设置为公开）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "设置文件公开状态",
                "parameters": [
                    {
                        "description": "设置公开状态请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.SetFilePublicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或加密文件不能公开",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "支持小文件直传和大文件分片上传",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "文件上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "预检ID",
                        "name": "precheck_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件数据",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分片索引",
                        "name": "chunk_index",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "总分片数",
                        "name": "total_chunks",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "分片MD5",
                        "name": "chunk_md5",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "是否加密",
                        "name": "is_enc",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "上传失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/clean-expired": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "清理过期的未完成上传任务。如果提供 userID 参数，则只清理该用户的过期任务；如果不提供，则清理所有用户的过期任务（系统自动清理）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "清理过期的上传任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID（可选，不提供则清理所有用户的过期任务）",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "清理结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "清理失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的上传任务（从数据库中删除记录）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除上传任务",
                "parameters": [
                    {
                        "description": "删除请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.DeleteUploadTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/expired": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询当前用户所有过期的上传任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "查询过期的上传任务列表",
                "responses": {
                    "200": {
                        "description": "过期的上传任务列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/precheck": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传前的预检查，检查空间、秒传可能性，返回预检ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "文件上传预检",
                "parameters": [
                    {
                        "description": "预检请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UploadPrecheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "秒传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "预检失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/progress": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据预检ID查询文件上传进度",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "查询上传进度",
                "parameters": [
                    {
                        "type": "string",
                        "description": "预检ID",
                        "name": "precheck_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "进度信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/myobj_src_core_domain_response.UploadProgressResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "预检信息不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/renew": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "延期过期的上传任务，延长过期时间使其可以继续上传",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "延期过期任务（恢复任务）",
                "parameters": [
                    {
                        "description": "延期请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.RenewExpiredTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "延期成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "任务不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "延期失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/file/upload/uncompleted": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询当前用户所有未完成的上传任务（用于断点续传）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "查询未完成的上传任务列表",
                "responses": {
                    "200": {
                        "description": "未完成的上传任务列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/recycled/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从回收站永久删除文件，不可恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "永久删除文件",
                "parameters": [
                    {
                        "description": "删除请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.DeleteRecycledRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/recycled/empty": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "清空当前用户回收站中的所有文件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "清空回收站",
                "responses": {
                    "200": {
                        "description": "清空成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "清空失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/recycled/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户回收站中的文件列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "获取回收站列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "回收站列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/recycled/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从回收站还原文件到原位置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "还原文件",
                "parameters": [
                    {
                        "description": "还原请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.RestoreFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "还原成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "500": {
                        "description": "还原失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/apiKey/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除指定的API Key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除API Key",
                "parameters": [
                    {
                        "description": "删除API Key请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.DeleteApiKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或删除失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "API Key不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/apiKey/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为用户生成新的API Key，用于API调用认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "生成API Key",
                "parameters": [
                    {
                        "description": "生成API Key请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.GenerateApiKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "生成成功，返回API Key和公钥",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或生成失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/apiKey/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有API Key列表（Key已掩码）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取API Key列表",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "object"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/challenge": {
            "get": {
                "description": "获取RSA公钥和挑战值，用于密码加密传输",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取登录挑战值",
                "responses": {
                    "200": {
                        "description": "挑战值信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户通过用户名和密码登录系统，返回JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误或登录失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "注册新用户账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或注册失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/setFilePassword": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "设置用户文件加密密码（首次设置）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "设置文件加密密码",
                "parameters": [
                    {
                        "description": "设置文件密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserUpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或设置失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/sysInfo": {
            "get": {
                "description": "获取系统配置和初始化状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "获取系统初始化信息",
                "responses": {
                    "200": {
                        "description": "系统信息",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/updateFilePassword": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改用户文件加密密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改文件加密密码",
                "parameters": [
                    {
                        "description": "修改文件密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserUpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或修改失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/updatePassword": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改用户登录密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改登录密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserUpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或修改失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/user/updateUser": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前用户的基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "更新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误或更新失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/video/play/precheck": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "验证权限并生成24小时有效的播放 Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "视频播放"
                ],
                "summary": "创建视频播放预检",
                "parameters": [
                    {
                        "description": "预检请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/myobj_src_core_domain_request.VideoPlayPrecheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "播放 Token",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/myobj_src_core_domain_response.VideoPlayTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        },
        "/video/stream": {
            "get": {
                "description": "基于播放 Token 流式传输视频，支持 Range 请求",
                "produces": [
                    "video/mp4"
                ],
                "tags": [
                    "视频播放"
                ],
                "summary": "视频流播放",
                "parameters": [
                    {
                        "type": "string",
                        "description": "播放 Token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bytes=0-",
                        "description": "Range 请求头",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "206": {
                        "description": "视频流数据"
                    },
                    "400": {
                        "description": "请求失败",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "403": {
                        "description": "Token 无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    },
                    "404": {
                        "description": "文件不存在",
                        "schema": {
                            "$ref": "#/definitions/myobj_src_pkg_models.JsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "myobj_src_core_domain_request.CreateLocalFileDownloadRequest": {
            "type": "object",
            "required": [
                "file_id"
            ],
            "properties": {
                "file_id": {
                    "description": "文件ID",
                    "type": "string"
                },
                "file_password": {
                    "description": "文件解密密码（加密文件必需）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.DeleteApiKeyRequest": {
            "type": "object",
            "required": [
                "api_key_id"
            ],
            "properties": {
                "api_key_id": {
                    "description": "API Key ID",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_request.DeleteDirRequest": {
            "type": "object",
            "required": [
                "dir_id"
            ],
            "properties": {
                "dir_id": {
                    "description": "目录ID",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_request.DeleteFileRequest": {
            "type": "object",
            "required": [
                "file_ids"
            ],
            "properties": {
                "file_ids": {
                    "description": "文件ID列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "myobj_src_core_domain_request.DeleteRecycledRequest": {
            "type": "object",
            "required": [
                "recycled_id"
            ],
            "properties": {
                "recycled_id": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.DeleteUploadTaskRequest": {
            "type": "object",
            "required": [
                "task_id"
            ],
            "properties": {
                "task_id": {
                    "description": "任务ID（预检ID）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.GenerateApiKeyRequest": {
            "type": "object",
            "properties": {
                "expires_days": {
                    "description": "过期天数，0表示永不过期",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_request.ParseTorrentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "description": "种子文件内容（Base64编码）或磁力链接（magnet:开头）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.PublicFileListRequest": {
            "type": "object",
            "required": [
                "page",
                "pageSize"
            ],
            "properties": {
                "page": {
                    "description": "页码（从1开始）",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "每页数量",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "sortBy": {
                    "description": "排序字段（name, size, time）",
                    "type": "string"
                },
                "type": {
                    "description": "文件类型",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.RenameDirRequest": {
            "type": "object",
            "required": [
                "dir_id",
                "new_dir_name"
            ],
            "properties": {
                "dir_id": {
                    "description": "目录ID",
                    "type": "integer"
                },
                "new_dir_name": {
                    "description": "新目录名",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.RenameFileRequest": {
            "type": "object",
            "required": [
                "file_id",
                "new_file_name"
            ],
            "properties": {
                "file_id": {
                    "description": "文件ID（uf_id）",
                    "type": "string"
                },
                "new_file_name": {
                    "description": "新文件名",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.RenewExpiredTaskRequest": {
            "type": "object",
            "required": [
                "task_id"
            ],
            "properties": {
                "days": {
                    "description": "延期天数（默认7天）",
                    "type": "integer"
                },
                "task_id": {
                    "description": "任务ID（预检ID）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.RestoreFileRequest": {
            "type": "object",
            "required": [
                "recycled_id"
            ],
            "properties": {
                "recycled_id": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.SetFilePublicRequest": {
            "type": "object",
            "required": [
                "file_id",
                "public"
            ],
            "properties": {
                "file_id": {
                    "description": "文件ID（uf_id）",
                    "type": "string"
                },
                "public": {
                    "description": "是否公开",
                    "type": "boolean"
                }
            }
        },
        "myobj_src_core_domain_request.StartTorrentDownloadRequest": {
            "type": "object",
            "required": [
                "content",
                "file_indexes"
            ],
            "properties": {
                "content": {
                    "description": "种子文件内容（Base64编码）或磁力链接",
                    "type": "string"
                },
                "enable_encryption": {
                    "description": "是否加密存储",
                    "type": "boolean"
                },
                "file_indexes": {
                    "description": "要下载的文件索引列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "virtual_path": {
                    "description": "保存的虚拟路径（可选，默认为/离线下载/）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.UploadPrecheckRequest": {
            "type": "object",
            "properties": {
                "chunk_signature": {
                    "description": "文件hash签名",
                    "type": "string"
                },
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                },
                "file_size": {
                    "description": "文件大小 字节",
                    "type": "integer"
                },
                "files_md5": {
                    "description": "文件分片的DM5列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path_id": {
                    "description": "路径ID",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "challenge": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.UserRegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "challenge": {
                    "description": "挑战ID",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.UserUpdatePasswordRequest": {
            "type": "object",
            "properties": {
                "challenge": {
                    "description": "挑战ID",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "new_passwd": {
                    "type": "string"
                },
                "old_passwd": {
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.UserUpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "用户邮箱",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "用户手机号",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_request.VideoPlayPrecheckRequest": {
            "type": "object",
            "required": [
                "file_id"
            ],
            "properties": {
                "file_id": {
                    "description": "文件ID",
                    "type": "string"
                },
                "share_password": {
                    "description": "分享密码（如果是分享链接访问）",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_response.ParseTorrentResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "description": "文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/myobj_src_core_domain_response.TorrentFileInfo"
                    }
                },
                "info_hash": {
                    "description": "InfoHash（种子唯一标识）",
                    "type": "string"
                },
                "name": {
                    "description": "种子名称",
                    "type": "string"
                },
                "total_size": {
                    "description": "总大小（字节）",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_response.StartTorrentDownloadResponse": {
            "type": "object",
            "properties": {
                "task_count": {
                    "description": "创建的任务数量",
                    "type": "integer"
                },
                "task_ids": {
                    "description": "创建的任务ID列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "torrent_name": {
                    "description": "种子名称",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_response.TorrentFileInfo": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "文件索引",
                    "type": "integer"
                },
                "name": {
                    "description": "文件名",
                    "type": "string"
                },
                "path": {
                    "description": "文件路径（种子内的相对路径）",
                    "type": "string"
                },
                "size": {
                    "description": "文件大小（字节）",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_response.UploadProgressResponse": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "is_complete": {
                    "description": "是否已完成",
                    "type": "boolean"
                },
                "md5": {
                    "description": "已上传分片的MD5列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "precheck_id": {
                    "type": "string"
                },
                "progress": {
                    "description": "进度百分比 (0-100)",
                    "type": "number"
                },
                "total": {
                    "description": "总分片数",
                    "type": "integer"
                },
                "uploaded": {
                    "description": "已上传分片数",
                    "type": "integer"
                }
            }
        },
        "myobj_src_core_domain_response.VideoFileInfo": {
            "type": "object",
            "properties": {
                "file_id": {
                    "description": "文件ID",
                    "type": "string"
                },
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                },
                "file_size": {
                    "description": "文件大小（字节）",
                    "type": "integer"
                },
                "is_enc": {
                    "description": "是否加密",
                    "type": "boolean"
                },
                "mime_type": {
                    "description": "MIME 类型",
                    "type": "string"
                }
            }
        },
        "myobj_src_core_domain_response.VideoPlayTokenResponse": {
            "type": "object",
            "properties": {
                "file_info": {
                    "description": "文件信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/myobj_src_core_domain_response.VideoFileInfo"
                        }
                    ]
                },
                "play_token": {
                    "description": "播放 Token（24小时有效）",
                    "type": "string"
                }
            }
        },
        "myobj_src_pkg_models.JsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "状态",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key 身份验证",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BearerAuth": {
            "description": "输入 \"Bearer {token}\" 进行身份验证",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "MyObj 文件存储系统 API",
	Description:      "MyObj 是一个功能强大的文件存储系统，支持文件上传、下载、分享、回收站等功能\n支持大文件分片上传、秒传、文件加密等高级特性",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
